### ISSUE TITLE
some inputs

### ISSUE THREAD

**Issue by test2a** [PhillipKN/pdf-bank-statement-analyzer#1]
hi. found your repo and would like to give my suggestions.
1. please set a license 
2. there is no requirements.txt so there are some packages that are missing
3. how to get started? there are 3 .py files but i am not sure which one to go with first as the readme is a bit lacking

**Comment by thubamamba** [comment]
Hey @test2a, here to agree with you. Also, check out this [article](https://python.plainenglish.io/visualize-your-pdf-bank-statement-with-python-cc3608d72a3) by @PhillipKN.
